version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rockyroadrocco001!
      POSTGRES_DB: bi_dashboard
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data  # persistent storage

  pgadmin:
    image: dpage/pgadmin4
    container_name: bi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
